---
- hosts: all
  become: yes

  tasks:

    - name: create users and setup the directories
      include: tasks/users.yml

    - name: install packages
      include: tasks/nginx.yml

  handlers:
    - name: restart nginx ubuntu
      service: name=nginx state=restarted enabled=yes
      become: yes
 
