    - name: create my user
      user:
        name: alpha
        shell: /bin/bash
        password: $6$/u3Axrxfc$aOpKw621QV7AkduPDuFbHIbTALq9J2kPrderwT1vs2yEzpS1C3ZRCZ7H8VHhKc4JmgPRvjUn7QAk0DKGVo8N90
        home: /home/alpha
        create_home: yes
        groups: sudo


    - name: create necessary directories
      file:
        state: directory
        path: /home/alpha/.ssh/
        owner: alpha
        group: alpha
        mode: 0755

    - name: add ssh key to siddiq08 user
      copy:
        src: /home/danish/.ssh/id_rsa.pub
        dest: /home/alpha/.ssh/authorized_keys
        owner: alpha
        group: alpha
        mode: 0644
